### PR TITLE
add chapter 2

### PR DESCRIPTION
**Pull request by Krit0016**
Add chapter 2 to the intro.md file

### CODE REVIEW

**Review by Nmorakinyo — COMMENTED** [review]
Nice plot twist on your story Cecile, But we need to add some quotation marks to each saying sentence.

**Comment by Krit0016** [comment]
> Nice plot twist on your story Cecile, But we need to add some quotation marks to each saying sentence.

Thanks, Nathan but I don't think I have a saying sentence in my story. However, I'm looking forward to seeing your next part of the story

**Comment by CecileSChapman** [comment]
You need to add a choice intro the intro.md file and put your next part of the story into a **new** file.

The choice should link to the new file you create.

**Comment by Krit0016** [comment]
> You need to add a choice intro the intro.md file and put your next part of the story into a **new** file.
> 
> The choice should link to the new file you create.

what is the choice ?

**Comment by Nmorakinyo** [comment]
Maybe we can add a chapter 3 in the story known as "Whispering Winds".

**Comment by maia0004** [comment]
sure, I can make chapter 3 since Maisie also did the chapter 2
________________________________

**Comment by Krit0016** [comment]
let me try to add a choice first when I make change i'll let you know

**Comment by maia0004** [comment]
ok, I'll be looking for this assignment around 7pm
________________________________

**Comment by CecileSChapman** [comment]
> > You need to add a choice intro the intro.md file and put your next part of the story into a **new** file.
> > The choice should link to the new file you create.
> 
> what is the choice ?

In a choose your own adventure story, the reader picks an action of what they want to do next to progress the story. Each member needs to add an action the reader can choose after the intro asks "What will you do next?". 

For example... 

Choice 1: Retrace your steps

The user clicks this option and it leads them to a new page, with what happens when they try to retrace their steps. You can make the story go in whichever direction you want after they choose this option.

**Comment by CecileSChapman** [comment]
Everybody is pretty much making their own Chapter 2, each on separate files. NOT on the intro.md file...

The story goes in different paths, and what you guys add should not be related to each other. 

Only add 1 choice each to the intro.md file.

Then, carry on the story in a new file. 

Let me know if you guys want to set up a group call on discord or zoom to figure it out.

**Comment by maia0004** [comment]
I'm ok doing a Zoom call starting 7:40 pm
________________________________

**Review by Krit0016 — COMMENTED** [review]
Hi team, I have add a choice 1 and the story of the choice please see the change

**Comment by CecileSChapman** [comment]
> Hi team, I have add a choice 1 and the story of the choice please see the change

Thank you Maisie! This is correct, I will merge it once everybody else is finished.

Please look at Maisie's branch if you need an example.

**Comment by Krit0016** [comment]
> > Hi team, I have add a choice 1 and the story of the choice please see the change
> 
> Thank you Maisie! This is correct, I will merge it once everybody else is finished.
> 
> Please look at Maisie's branch if you need an example.

Thanks, Cecile

**Comment by Krit0016** [comment]
> Everybody is pretty much making their own Chapter 2, each on separate files. NOT on the intro.md file...
> 
> The story goes in different paths, and what you guys add should not be related to each other.
> 
> Only add 1 choice each to the intro.md file.
> 
> Then, carry on the story in a new file.
> 
> Let me know if you guys want to set up a group call on discord or zoom to figure it out.

i think we should have some zoom call to help finish the next stage

**Comment by maia0004** [comment]
Ana Carolina Cardoso Maia is inviting you to a scheduled Zoom meeting.

Topic: Ana Carolina Cardoso Maia's Personal Meeting Room

Join Zoom Meeting
https://us05web.zoom.us/j/9836936552?pwd=SjVLTWhjd1NvWjMrS1JIalJ3OHgwZz09

Meeting ID: 983 693 6552
Passcode: 0d9gVZ



________________________________

**Pull request merged**
