### PR TITLE
Maia0004

### PR DESCRIPTION
**Pull request by maia0004**
I made the changes that were necessary, please, take a look

### CODE REVIEW

**Comment by CecileSChapman** [comment]
> I made the changes that were necessary, please, take a look

Thank you Lina, your edit looks good.

**Comment by maia0004** [comment]
Nathan, are your class is going to be at 7pm?
________________________________

**Comment by maia0004** [comment]
If possible, talk with me at discord, Nathan
________________________________

**Comment by maia0004** [comment]
my name in discord is Lina CM
________________________________

**Comment by maia0004** [comment]
I'm waiting for you in building C, Nathan
________________________________

**Pull request merged**
