### PR TITLE
Maia0004

### PR DESCRIPTION
**Pull request by maia0004**
I followed Maisie's story, please, take a look

### CODE REVIEW

**Comment by CecileSChapman** [comment]
> I followed Maisie's story, please, take a look

You're almost there, but your part should not follow Maisie's chapter, it should follow the intro. 

The reader won't see Maisie's chapter if they choose your option, so they haven't met a group.

**Comment by maia0004** [comment]
ok

________________________________

**Comment by CecileSChapman** [comment]
Just saw your changes, it's all good now.

**Comment by maia0004** [comment]
Ok, I did a second choice instead to keep with Maisie's story
________________________________

**Comment by Nmorakinyo** [comment]
I've got more choices for chapter 1

- Stand still
- Crawl on the Ground

**Comment by maia0004** [comment]
guys, I am not receiving notifications from my discord and I don't know what to do. I don't think that is a good idea keep talking through there
________________________________

**Pull request merged**
